### ISSUE TITLE
Use `master` branch by default (rather than `dev`)

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/mozilla-pipeline-schemas#278]
Follow up from #261, let's use `master` as expected.

cc @acmiyaguchi since this affects integration tests

**Comment by whd** [comment]
We should consider actually rolling this out, since it looks like we've been maintaining these branches at parity for some time. The pieces I'm aware of that need to change are integration tests, mozilla-schema-generator, and the default branch the ops jenkins job points at.

Maybe something for whistler?

**Comment by mreid-moz** [comment]
Yes, this is on my todo list to tackle while everyone's together in Whistler.

**Comment by acmiyaguchi** [comment]
Fixed in #352
