### ISSUE TITLE
Add back missing attributes to payload_bytes_decoded schema

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#377]
/CC @jklukas 

[Here's](https://github.com/mozilla-services/cloudops-infra/commit/a0d1bb4d94e81b72b6ff02031a95bf0391a0bf26#diff-1fec0cabf755a2a7b5c0b38b3963eec2) the version that is currently deployed. [Here's](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/59fedd57ea36c3ed9e09dbb32dc9a68761352f7c#diff-90730b5111929a4fca352a5b0f5584b4) the version newly-created on the generated-schemas branch. It appears we've dropped `metadata.document_*` somewhere along the line:

 	* google_bigquery_table.telemetry_tls_13_study_v3_v4_telemetry_decoded: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:payload_bytes_decoded.telemetry_telemetry__tls_13_study_v3_v4. Field metadata.document_namespace is missing in new schema, invalid

I'm not sure if we wanted these fields at the top level (as in the errors schema chase) or within `metadata` so I'm filing this as an issue instead of a PR. I'm thinking these are probably meant to be added to `ingestionCommonMetadata.1.schema.json` but I'm not 100%.

**Comment by jklukas** [comment]
For decoded, the `document_*` fields aren't needed because they're encoded in the table name itself. That said, it would be a nice usability improvement to be able to access those as distinct fields when querying sets of tables using wildcards rather than relying on parsing `_TABLE_SUFFIX`.

For the final-state BQ tables, we had decided to embed these `document_*` attributes inside the `metadata` field in the payload only for the purposes of being able to recover them if we needed to reprocess from error output in GCS and had lost PubSub attributes (as is the case for BQ streaming sink errors). We specifically decided not to include those fields in the final BQ schemas, because that would be duplicating information from the table name, and we want to follow a policy of having a single source of truth for each field rather than introducing ambiguity and having users be able to pick from several different fields for the same logical piece of information.

For these payload_bytes tables, I think there's less of an argument against duplicating information since these are intended mostly to be used for operational scenarios rather than analytics users. I'm inclined to go ahead and add these fields as `metadata.document_*` for the payload_bytes decoded schema to match with how we're storing them within the payload itself.

**Comment by whd** [comment]
To be clear, my assumption with the latest deploy was that the new schemas were going to be schema-compatible with the currently deployed schemas. I think it's reasonable not to redundantly encode this information, so if you'd prefer to back out #378 and destroy/recreate these tables that works for me as well.
