### ISSUE TITLE
Delete the "dev" branch

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/mozilla-pipeline-schemas#431]
This used to be the default target for pull requests, and has been the source of a lot of confusion. Now that we're back to working from the `master` branch, we should delete `dev` to minimize confusion (and make sure all the documentation is updated accordingly).

**Comment by brizental** [comment]
One note about this that caused some confuson for me today. Since the `dev` branch is not used anymore, this bullet shoud be removed from the README.md
> All pull requests must be made against the dev branch, direct commits to master are not permitted.

Gave me a little scare since I read this right after merging to `master`, hehe. Also the other bullet points probably don't mirror the way releases are done today since `dev` is not used anymore.

**Comment by acmiyaguchi** [comment]
The `dev` branch has been deleted. 👋
